// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Tags", testTags)
	t.Run("UserTagMaps", testUserTagMaps)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Tags", testTagsDelete)
	t.Run("UserTagMaps", testUserTagMapsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Tags", testTagsQueryDeleteAll)
	t.Run("UserTagMaps", testUserTagMapsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Tags", testTagsSliceDeleteAll)
	t.Run("UserTagMaps", testUserTagMapsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Tags", testTagsExists)
	t.Run("UserTagMaps", testUserTagMapsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Tags", testTagsFind)
	t.Run("UserTagMaps", testUserTagMapsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Tags", testTagsBind)
	t.Run("UserTagMaps", testUserTagMapsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Tags", testTagsOne)
	t.Run("UserTagMaps", testUserTagMapsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Tags", testTagsAll)
	t.Run("UserTagMaps", testUserTagMapsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Tags", testTagsCount)
	t.Run("UserTagMaps", testUserTagMapsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Tags", testTagsHooks)
	t.Run("UserTagMaps", testUserTagMapsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Tags", testTagsInsert)
	t.Run("Tags", testTagsInsertWhitelist)
	t.Run("UserTagMaps", testUserTagMapsInsert)
	t.Run("UserTagMaps", testUserTagMapsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("UserTagMapToTagUsingTag", testUserTagMapToOneTagUsingTag)
	t.Run("UserTagMapToUserUsingUser", testUserTagMapToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("TagToUserTagMaps", testTagToManyUserTagMaps)
	t.Run("UserToUserTagMaps", testUserToManyUserTagMaps)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("UserTagMapToTagUsingUserTagMaps", testUserTagMapToOneSetOpTagUsingTag)
	t.Run("UserTagMapToUserUsingUserTagMaps", testUserTagMapToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("TagToUserTagMaps", testTagToManyAddOpUserTagMaps)
	t.Run("UserToUserTagMaps", testUserToManyAddOpUserTagMaps)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Tags", testTagsReload)
	t.Run("UserTagMaps", testUserTagMapsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Tags", testTagsReloadAll)
	t.Run("UserTagMaps", testUserTagMapsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Tags", testTagsSelect)
	t.Run("UserTagMaps", testUserTagMapsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Tags", testTagsUpdate)
	t.Run("UserTagMaps", testUserTagMapsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Tags", testTagsSliceUpdateAll)
	t.Run("UserTagMaps", testUserTagMapsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
