// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserTagMaps(t *testing.T) {
	t.Parallel()

	query := UserTagMaps()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserTagMapsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTagMapsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserTagMaps().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTagMapsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserTagMapSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserTagMapsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserTagMapExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserTagMap exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserTagMapExists to return true, but got false.")
	}
}

func testUserTagMapsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userTagMapFound, err := FindUserTagMap(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userTagMapFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserTagMapsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserTagMaps().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserTagMapsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserTagMaps().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserTagMapsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userTagMapOne := &UserTagMap{}
	userTagMapTwo := &UserTagMap{}
	if err = randomize.Struct(seed, userTagMapOne, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}
	if err = randomize.Struct(seed, userTagMapTwo, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userTagMapOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userTagMapTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserTagMaps().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserTagMapsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userTagMapOne := &UserTagMap{}
	userTagMapTwo := &UserTagMap{}
	if err = randomize.Struct(seed, userTagMapOne, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}
	if err = randomize.Struct(seed, userTagMapTwo, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userTagMapOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userTagMapTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userTagMapBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func userTagMapAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserTagMap) error {
	*o = UserTagMap{}
	return nil
}

func testUserTagMapsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserTagMap{}
	o := &UserTagMap{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userTagMapDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserTagMap object: %s", err)
	}

	AddUserTagMapHook(boil.BeforeInsertHook, userTagMapBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userTagMapBeforeInsertHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.AfterInsertHook, userTagMapAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userTagMapAfterInsertHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.AfterSelectHook, userTagMapAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userTagMapAfterSelectHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.BeforeUpdateHook, userTagMapBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userTagMapBeforeUpdateHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.AfterUpdateHook, userTagMapAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userTagMapAfterUpdateHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.BeforeDeleteHook, userTagMapBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userTagMapBeforeDeleteHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.AfterDeleteHook, userTagMapAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userTagMapAfterDeleteHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.BeforeUpsertHook, userTagMapBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userTagMapBeforeUpsertHooks = []UserTagMapHook{}

	AddUserTagMapHook(boil.AfterUpsertHook, userTagMapAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userTagMapAfterUpsertHooks = []UserTagMapHook{}
}

func testUserTagMapsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserTagMapsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userTagMapColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserTagMapToOneTagUsingTag(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserTagMap
	var foreign Tag

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tagDBTypes, false, tagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tag struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TagID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Tag().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserTagMapSlice{&local}
	if err = local.L.LoadTag(ctx, tx, false, (*[]*UserTagMap)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tag == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Tag = nil
	if err = local.L.LoadTag(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tag == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserTagMapToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserTagMap
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userTagMapDBTypes, false, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UserTagMapSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UserTagMap)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUserTagMapToOneSetOpTagUsingTag(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserTagMap
	var b, c Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userTagMapDBTypes, false, strmangle.SetComplement(userTagMapPrimaryKeyColumns, userTagMapColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Tag{&b, &c} {
		err = a.SetTag(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Tag != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserTagMaps[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TagID != x.ID {
			t.Error("foreign key was wrong value", a.TagID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TagID))
		reflect.Indirect(reflect.ValueOf(&a.TagID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TagID != x.ID {
			t.Error("foreign key was wrong value", a.TagID, x.ID)
		}
	}
}
func testUserTagMapToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserTagMap
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userTagMapDBTypes, false, strmangle.SetComplement(userTagMapPrimaryKeyColumns, userTagMapColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserTagMaps[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserTagMapsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserTagMapsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserTagMapSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserTagMapsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserTagMaps().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userTagMapDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `TagID`: `integer`}
	_                 = bytes.MinRead
)

func testUserTagMapsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userTagMapPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userTagMapAllColumns) == len(userTagMapPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserTagMapsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userTagMapAllColumns) == len(userTagMapPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserTagMap{}
	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userTagMapDBTypes, true, userTagMapPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userTagMapAllColumns, userTagMapPrimaryKeyColumns) {
		fields = userTagMapAllColumns
	} else {
		fields = strmangle.SetComplement(
			userTagMapAllColumns,
			userTagMapPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserTagMapSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserTagMapsUpsert(t *testing.T) {
	t.Parallel()

	if len(userTagMapAllColumns) == len(userTagMapPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserTagMap{}
	if err = randomize.Struct(seed, &o, userTagMapDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserTagMap: %s", err)
	}

	count, err := UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userTagMapDBTypes, false, userTagMapPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserTagMap struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserTagMap: %s", err)
	}

	count, err = UserTagMaps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
